<?php

namespace App\Notifications;

use App\Models\User;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Sent to a nurse or physician when an admin creates their account, carrying
 * the one-time link that lets them set a password and activate it.
 *
 * The plaintext token only ever exists for the lifetime of this notification.
 * It is generated by Password::broker('staff_invitations')->createToken(),
 * which stores only a hash. Deliberately NOT queued: this project's queue
 * connection is 'database', so a queued job would serialize the plaintext
 * token into the jobs table until a worker picked it up — persisting the
 * very value the broker is designed to never store in the clear. Laravel's
 * own password-reset notification makes the same choice for the same reason.
 */
class StaffAccountInvitation extends Notification
{
    public function __construct(
        private readonly User $user,
        #[\SensitiveParameter] private readonly string $token,
    ) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $role = ucfirst($this->user->role);
        $expiresInDays = (int) ceil(config('auth.passwords.staff_invitations.expire') / 60 / 24);

        return (new MailMessage)
            ->subject('CLSU Telemedicine — Staff Account Invitation')
            ->greeting('Hello '.$this->user->first_name.',')
            ->line('An administrator has created a '.$role.' account for you on CLSU Telemedicine.')
            ->line('To get started, activate your account and create your own password.')
            ->action('Activate Account', $this->activationUrl())
            ->line("This invitation link expires in {$expiresInDays} days.")
            ->line('If you were not expecting this invitation, no action is required — the link will simply expire.');
    }

    private function activationUrl(): string
    {
        return route('staff.activate', [
            'token' => $this->token,
            'email' => $this->user->email,
        ]);
    }
}
